config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :users
  get 'archives/index'
  resources :posts
  root to: "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts

  


end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :category
  validates :name, :price, :description, :category_id, presence: true 

  def day
    self.created_at.strftime("%b %e, %Y")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # has_one_attached :avatar

  validates :username, presence: :true, uniqueness: { case_sensitive: false }
  validate :validate_username

   def validate_username
     if User.where(email: username).exists?
       errors.add(:username, :invalid)
     end
   end

   def self.login
    self.username || self.email
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  attr_accessor :posts

  def index
    @posts = Post.all.group_by(&:day)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :price, :description, :location, :image, :category_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :location, :posts, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/archives/index.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-half">
    <% @posts.each do |day, posts| %>
      <h3 class="is-size-4 has-text-weight-bold mb-4 has-text-centered">
        Posts for <%= day %></h3>
      <% posts.each do |post| %>
        <%= link_to post_path(post) do %>
          <div class="card-content">
            <strong> <%= post.name %> </strong><br/>
            Price: $ <%= post.price %><br/>
            Description: <%= post.description %><br/>
            Location: <%= post.location %><br/>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Puzzle Trader</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "shared/header" %>
    <% if notice.present? %>
      <div class="notification is-link is-light"> <%= notice %> </div>
    <% end %>

    <% if alert.present? %>
      <div class="notification is-danger is-light"> <%= alert %> </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.haml
- categories = Category.all.pluck(:name, :id)
= form_with(model: post, local: true) do |form|
  - if post.errors.any?
    .message.is-danger
      .message-header
        %p
          = pluralize(post.errors.count, "error")
          prohibited this post from being saved:
      .message-body
        %ul
          - post.errors.full_messages.each do |message|
            %li= message
  .field
    = form.label :name, class: "label"
    = form.text_field :name, class: "input"
  .field
    = form.label :price, class: "label"
    = form.number_field :price, class: "input"
  .field
    = form.label :description, class: "label"
    = form.text_field :description, class: "input"
  .field
    = form.label :location, class: "label"
    = form.text_field :location, class: "input"
  .field
    = form.label :category, class: "label"
    .select
      = form.select :category_id, categories
  .field
    = form.label "Add A Picture", class: "label"
    = form.file_field :image, accept: 'image/png,image/gif,image/jpeg'
  .actions
    = form.submit class: "button is-success"
    -# %span.file.has-name.file-icon.file-cta
    -#   %i.fa.fa-upload

app/views/posts/edit.html.haml
.mt-6{class: "columns.is-centered"}
  .column.is-one-third
    %h1.is-size-2.has-text-weight-bold.mb-3 Edit Your Post
    = render 'form', post: @post
    = link_to 'Back', posts_path

app/views/posts/index.html.haml
%body
  - content_for :title do
    Puzzle Trader
  .columns.mt-6.is-centered
    - @posts.each do |post|
      .column.is-one-quarter
        .card
          %header.card-header
            %p.card-header-title
              = post.name
          .card-content
            .content
              %p.has-text-weight-bold Price:
              %p= "$#{post.price}"
              %p.has-text-weight-bold Description:
              %p= post.description
              %p.has-text-weight-bold Location:
              %p= post.location
              %p.has-text-weight-bold Posted At:
              %p.italic= "#{time_ago_in_words(post.created_at)} ago"
          .card-footer
            = link_to 'View', post, class: "card-footer-item"
            = link_to 'Edit', edit_post_path(post), class: "card-footer-item"
            = link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "card-footer-item"
  .columns.is-centered.mt-6
    = link_to "View All Posts", archives_index_path, class: "button is-link is-outlined is-centered"

app/views/posts/new.html.haml
.mt-6{class: "columns.is-centered"}
  .column.is-one-third
    %h1.is-size-4.has-text-weight-bold.mb-6 Post Your Puzzle
    = render 'form', post: @post
    = link_to 'Back', posts_path

app/views/posts/show.html.haml
- category = Category.find(@post.category_id)

%body
  .columns.mt-6.is-centered
    .column.is-one-quarter
      %header.has-text-weight-bold
        %p
          = @post.name
      %br
      %p.has-text-weight-bold Price:
      %p= "$#{@post.price}"
      %p.has-text-weight-bold Description:
      %p= @post.description
      %p.has-text-weight-bold Location:
      %p= @post.location
      %p.has-text-weight-bold Category:
      %p= category.name
      %p.has-text-weight-bold Posted:
      %p.italic= "#{time_ago_in_words(@post.created_at)} ago"
    - if @post.image.attached?
      %image{src: "#{(url_for(@post.image))}"}

app/views/shared/_header.html.erb
<section class="hero is-primary is-small">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to root_path, class: "navbar-item" do %>
            <span class="has-text-white is-size-4">Puzzle Trader</span>
          <% end %>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong>.
              <%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link' %> |
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link'  %>
              <% else %>
              <%= link_to "Sign up", new_user_registration_path, class: 'navbar-link'  %>
              <%= link_to "Login", new_user_session_path, class: 'navbar-link'  %>
              <% end %>
          </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        <% if content_for(:title) %>
          <%= yield :title %>
        <% else %>
          Puzzle Trader
        <% end %>
      </h1>
      <h2 class="subtitle">
        Buy Or Trade Your Favorite Puzzles
      </h2>
    </div>
  </div>

  <!-- Hero footer: will stick at the bottom -->
  <div class="hero-foot">
    <nav class="tabs">
      <div class="container">
        <ul>
          <li>
            <%= link_to "Create New Post", new_post_path %>
          </li>
          <li><%= link_to "See Your Posts", posts_path %></li>
        </ul>
      </div>
    </nav>
  </div>
</section>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :posts %>
    <%= form.number_field :posts %>
  </div>

  <div class="field">
    <%= form.label "Profile Picture" %>
    <%= form.file_field :avatar %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Location</th>
      <th>Posts</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.location %></td>
        <td><%= user.posts %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Your Puzzles', posts_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<% if @user.avatar.attached? %>
	<image src="<%=(url_for(@user.avatar))%>">
<% end %>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user.location %>
</p>

<p>
  <strong>Posts:</strong>
  <%= @user.posts %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>